[package]
edition = "2024"
name = "httproxy"
version = "0.1.9"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[dependencies]
anyhow = "1.0"
axum = {version = "0.8.8", features = ["http2", "macros"]}
bytes = "1.5"
clap = {version = "4.5.54", features = ["derive"]}
domain = "0.11.1"
futures = "0.3"
h2 = "0.4.13"
http = "1.0"
http-body = "1.0"
http-body-util = "0.1"
httparse = "1.8"
jsonwebtoken = {version = "10.2.0", features = ["aws_lc_rs"]}
moka = {version = "0.12", features = ["future"]}
pin-project-lite = "0.2.16"
rand = "0.9.2"
rand_distr = "0.5.1"
rustls = "0.23.36"
serde = {version = "1.0", features = ["derive"]}
singleflight-async = "0.2.0"
tokio = {version = "1.49.0", features = ["full"]}
tokio-rustls = "0.26.4"
tokio-socks = "0.5.2"
tokio-stream = {version = "0.1", features = ["net"]}
toml = "0.9.11"
tower = "0.5.2"
tower-http = {version = "0.6", features = ["trace"]}
tracing = "0.1"
tracing-appender = "0.2.4"
tracing-subscriber = {version = "0.3", features = [
  "env-filter",
  "chrono",
  "json",
]}
url = "2"
webpki-roots = "1.0.5"
wreq = "6.0.0-rc.26"
wreq-util = "3.0.0-rc.9"
